# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.15.1'
  displayName: 'Install Node'
- script: npm install
  displayName: 'Install dependencies'
- script: npm run test:lint:js
  displayName: 'Run JS lint'
- script: npm run test:lint:css
  displayName: 'Run CSS lint'
- script: npm run test:unit -- --coverage . --watchAll=false
  displayName: 'Run unit tests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
  displayName: 'Publish Code Coverage'